
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jul 28 17:24:46 CST 2020
//----------------------------------------------------

package tarea2compi2;

import java_cup.runtime.Symbol;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Tue Jul 28 17:24:46 CST 2020
  */
public class AnalizadorSintacticoT2 extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public AnalizadorSintacticoT2() {super();}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintacticoT2(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintacticoT2(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\010\000\002\002\004\000\002\002\005\000\002\002" +
    "\003\000\002\003\004\000\002\003\003\000\002\004\003" +
    "\000\002\005\004\000\002\005\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\014\000\006\003\005\004\007\001\002\000\006\004" +
    "\ufffd\005\ufffd\001\002\000\004\002\uffff\001\002\000\006" +
    "\004\007\005\012\001\002\000\010\002\ufffc\004\ufffc\005" +
    "\ufffc\001\002\000\004\002\011\001\002\000\004\002\001" +
    "\001\002\000\004\004\007\001\002\000\006\004\ufffe\005" +
    "\ufffe\001\002\000\006\002\ufffa\004\007\001\002\000\004" +
    "\002\000\001\002\000\004\002\ufffb\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\014\000\010\002\007\003\005\004\003\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\004\012\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\004\013\005\014\001\001\000\002\001\001\000\006" +
    "\004\013\005\015\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSintacticoT2$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSintacticoT2$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSintacticoT2$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    
    /**private Symbol s;
    public void syntaxError(Symbol s){
        this.s = s;
    }
    public Symbol getS(Symbol s){
        return this.s = s;
    }

    public void setAccion(String tipo,String mensaje,String accion){
            System.out.println(tipo+"         "+mensaje);
        }

    public void syntax_error(Symbol s){
            if(s!=null){
                setAccion("ERROR","Error Sintaxis token: Linea: " + (s.right+1) + ",   Columna: " + (s.left+1) + ",  Simbolo: " + s.value, "");
            }
    }**/


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$AnalizadorSintacticoT2$actions {


    int bandera = 0;
    
    public int convertirNumero(Object o){
        try {
		int val = Integer.parseInt((String) o);
		return val;
	}catch (ClassCastException ex){
		int val = (int) o;
		return val;
	}
    }

  private final AnalizadorSintacticoT2 parser;

  /** Constructor */
  CUP$AnalizadorSintacticoT2$actions(AnalizadorSintacticoT2 parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintacticoT2$do_action(
    int                        CUP$AnalizadorSintacticoT2$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintacticoT2$parser,
    java.util.Stack            CUP$AnalizadorSintacticoT2$stack,
    int                        CUP$AnalizadorSintacticoT2$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalizadorSintacticoT2$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSintacticoT2$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // S ::= T 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoT2$stack.peek()).value;
		 RESULT = (Double)a/2; 
              CUP$AnalizadorSintacticoT2$result = parser.getSymbolFactory().newSymbol("S",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoT2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // S ::= T S 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.elementAt(CUP$AnalizadorSintacticoT2$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.elementAt(CUP$AnalizadorSintacticoT2$top-1)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoT2$stack.elementAt(CUP$AnalizadorSintacticoT2$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoT2$stack.peek()).value;
		 double op = ((Double)a+((Double)b))/2; RESULT = op; 
              CUP$AnalizadorSintacticoT2$result = parser.getSymbolFactory().newSymbol("S",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.elementAt(CUP$AnalizadorSintacticoT2$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoT2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // T ::= DIGITO 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoT2$stack.peek()).value;
		 RESULT = a; 
              CUP$AnalizadorSintacticoT2$result = parser.getSymbolFactory().newSymbol("T",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoT2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // E ::= T 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoT2$stack.peek()).value;
		RESULT = a; 
              CUP$AnalizadorSintacticoT2$result = parser.getSymbolFactory().newSymbol("E",1, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoT2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // E ::= E T 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.elementAt(CUP$AnalizadorSintacticoT2$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.elementAt(CUP$AnalizadorSintacticoT2$top-1)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoT2$stack.elementAt(CUP$AnalizadorSintacticoT2$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoT2$stack.peek()).value;
		 double op = ((Double)a*2)+(Double)b; RESULT = op; 
              CUP$AnalizadorSintacticoT2$result = parser.getSymbolFactory().newSymbol("E",1, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.elementAt(CUP$AnalizadorSintacticoT2$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoT2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INICIO ::= error 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoT2$stack.peek()).value;
		parser.syntax_error((Symbol)e);
              CUP$AnalizadorSintacticoT2$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoT2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= E PUNTO S 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.elementAt(CUP$AnalizadorSintacticoT2$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.elementAt(CUP$AnalizadorSintacticoT2$top-2)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoT2$stack.elementAt(CUP$AnalizadorSintacticoT2$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoT2$stack.peek()).value;
		System.out.println("El Numero es: "+(Double)((Double)a+(Double)b));
              CUP$AnalizadorSintacticoT2$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.elementAt(CUP$AnalizadorSintacticoT2$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintacticoT2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.elementAt(CUP$AnalizadorSintacticoT2$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.elementAt(CUP$AnalizadorSintacticoT2$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintacticoT2$stack.elementAt(CUP$AnalizadorSintacticoT2$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSintacticoT2$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.elementAt(CUP$AnalizadorSintacticoT2$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintacticoT2$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSintacticoT2$parser.done_parsing();
          return CUP$AnalizadorSintacticoT2$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

