
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 30 16:16:06 CST 2020
//----------------------------------------------------

package tarea2compi2;

/** CUP generated class containing symbol constants. */
public class SimbolosT2 {
  /* terminals */
  public static final int PUNTO = 3;
  public static final int error = 1;
  public static final int DIGITO = 2;
  public static final int EOF = 0;
}

